version: '3.8'

services:
  backend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: echo-sample
    volumes:
      - '.:/go/src/app'
    ports:
      - '9005:9005'
    tty: true
    stdin_open: true
